[build-system]
requires = ["flit_scm"]
build-backend = "flit_scm:buildapi"

[project]
name = "dserver-retrieve-plugin-mongo"
description = "Retrieve plugin for dserver using mongodb"
readme = "README.rst"
license = {text = "MIT"}
authors = [
    {name = "Tjelvar Olsson", email = "tjelvar.olsson@gmail.com"},
    {name = "Johannes L. Hörmann", email = "johannes.laurin@gmail.com"},
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "pymongo",
    "PyYAML",
    "dtoolcore>=3.18.0",
    "dservercore"
]

[project.optional-dependencies]
test = [
    "dservercore",
    "dserver-search-plugin-mongo",
    "pytest",
    "pytest-cov",
]

[project.urls]
Documentation = "https://github.com/jic-dtool/dserver-retrieve-plugin-mongo/blob/main/README.rst"
Repository = "https://github.com/jic-dtool/dserver-retrieve-plugin-mongo"
Changelog = "https://github.com/jic-dtool/dserver-retrieve-plugin-mongo/blob/main/CHANGELOG.rst"

[project.entry-points."dservercore.retrieve"]
MongoRetrieve = "dserver_retrieve_plugin_mongo.utils_retrieve:MongoRetrieve"

[tool.flit.module]
name = "dserver_retrieve_plugin_mongo"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "dserver_retrieve_plugin_mongo/version.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=dserver_retrieve_plugin_mongo --cov-report=term-missing"
