name: test
on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
        dtool-lookup-server-version: [ master ]
        dserver-search-plugin-mongo-version: [ main ]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Set up python3 ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Set up pytest environment
      run: |
        python -m pip install --upgrade pip
        # The following line comes in handy when versioning and packaging 
        pip install --upgrade setuptools wheel setuptools-scm[toml] importlib-metadata
        pip install flake8 pytest pytest-cov

    - name: Install server refactor and search plugin
      run: | 
        # This should move into the strategy matrix once released
        pip install git+https://github.com/jic-dtool/dtool-lookup-server.git@${{ matrix.dtool-lookup-server-version }}
        pip install git+https://github.com/livMatS/dserver-search-plugin-mongo.git@${{ matrix.dserver-search-plugin-mongo-version }}

    - name: Install own requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
        pip list
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -sv
